version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_con
    environment:
      PGADMIN_DEFAULT_EMAIL: kh.mukhtar60@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    
  web:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
volumes:
  postgres_data:
    name: click_book_postgres_data
  pgadmin_data:
    name: click_book_pgadmin_data




